### ISSUE TITLE
Updating status icon for newer window managers

### ISSUE THREAD

**Issue by stereotypy** [gatopeich/gatotray#5]
Hi, I don't know if this project is still active but I really love having the graphical tray monitor. I am on Budgie and recently with the update the tray icon no longer shows (https://github.com/BuddiesOfBudgie/budgie-desktop/issues/446)

Any way this could be updated to using a newer tray library? thanks

**Comment by gatopeich** [comment]
Problem with new icons is that they are usually monochrome and static. I use a systray plugin on Mint, can you try that?

**Comment by stereotypy** [comment]
Yeah, it's just not usable on Budgie, switched to Cinnamon/openbox now and works like a charm! Thanks

**Comment by gatopeich** [comment]
I might look at this in the future.
